// Code generated by logcopter-gen; DO NOT EDIT.

package serve

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.publish-vault.cmd.retro-obsidian-publish.commands.serve")
